### ISSUE TITLE
desktop-sidecar Crashloopbackoff

### ISSUE THREAD

**Issue by nataliagranato** [pod-arcade/charts#1]
I installed the chart on the cluster, but the desktop container has an error, see the log below:

Generating self-signed certificate...
2023-12-28T05:16:10.112000450Z WebSocket server settings:
2023-12-28T05:16:10.112079129Z - Listen on :7900
2023-12-28T05:16:10.112163108Z - Web server. Web root: /usr/share/novnc
2023-12-28T05:16:10.112223092Z - SSL/TLS support
2023-12-28T05:16:10.112272965Z - Backgrounding (daemon)
2023-12-28T05:16:10.117007454Z noVNC should now be accessible via https://nataliagranato-desktop-sidecar-76c498f577-496jd:7900/
2023-12-28T05:16:10.169084391Z Recreating device nodes from /host/dev/dri/ to /dev/dri/...
2023-12-28T05:16:10.176645909Z Recreating device by-path...
2023-12-28T05:16:10.249650543Z Recreating device card0...
2023-12-28T05:16:10.305167489Z Warning: UINPUT_DEVICE_MODE=NONE. Gamepads may not function correctly.
2023-12-28T05:16:10.342983923Z ==> /var/log/pa-extra-commands.log <==
2023-12-28T05:16:10.342983923Z
2023-12-28T05:16:10.342983923Z ==> /var/log/pa-sway.log <==

**Comment by JohnCMcDonough** [comment]
Yeah, so this is probably related to an issue with automatically disabling hardware acceleration when no graphics card is present/passed through to the container. For now, you can set the environment variable `DISABLE_HW_ACCEL` to `"true"`. 

If that doesn't fix it, it might be helpful to see the rendered k8s resources, or your values overrides.

**Comment by JohnCMcDonough** [comment]
This seems even more likely now, looking at the environment variables set in the chart. A lot of these were hardcoded in to work with earlier versions of the desktop component, before it got smarter about auto-detecting things.

```yaml
  WLR_BACKENDS: headless                        # Should default correctly now and can be deleted
  DRI_DEVICE_MODE: MKNOD                        # Should default correctly now and can be deleted
  UINPUT_DEVICE_MODE: NONE                      # Should default correctly now and can be deleted
  DISABLE_HW_ACCEL: "false"                     # This should NOT be set, since it forcibly enables hardware acceleration
  WLR_RENDERER: gles2                           # Should default correctly now and can be deleted
  WLR_NO_HARDWARE_CURSORS: "1"                  # Should default correctly now and can be deleted

  FFMPEG_HARDWARE: "1"                          # I don't believe this is even in use anymore

  XDG_RUNTIME_DIR: /tmp/sway                    # This needs to be set
  PULSE_SERVER: unix:/tmp/pulse/pulse-socket    # This needs to be set
  DISPLAY: :0                                   # This needs to be set
```
